application: duzhangtesting
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
# - url: /getkarma
#   script: trademealpoints.application
#   secure: always
  
- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin
  
- url: /.*
  script: trademealpoints.application
  secure: never

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  
inbound_services:
- mail