application: trademealpoints
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: trademealpoints.application

- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin
  
- url: /getkarma/.*
  script: trademealpoints.application
  secure: always
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  
inbound_services:
- mail